version: "3.9"

services:
  user-microservice:
    container_name: user-microservice
    build: .
    networks:
      - polylink-network
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/polylink
      spring.datasource.username: root
      spring.datasource.password: password
      server.port: 8080

      # Kafka
      spring.kafka.bootstrap-servers: kafka:9092
      spring.kafka.consumer.group-id: polylink

      # App Properties
      jwtSecret: secret
      jwtExpirationMs: 86400000




networks:
  polylink-network:
    name: polylink-network
    external: true
