name: Deploy Staging to Dokku


on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@cluster-ig5.igpolytech.fr:22/stg-polylink-user-ms'
          ssh_private_key: ${{ secrets.DOKKU_SSH }}
